### ISSUE TITLE
Possible serious issue, please check

### ISSUE THREAD

**Issue by harshayburadkar** [intuit/oauth-jsclient#1]
The passing of tokens should be made mandatory in all API calls. 
Currently, when I test out the app with multiple users, the refresh happens for the last user's token regardless of whichever user requests it.

This problem is going to happen with other APIs too since library acts on this.token which will have the value of the last logged in user.

**Comment by abisalehalliprasan** [comment]
@harshayburadkar ,

The Client is designed in such a way that for every instance of the OAuth Library / SDK, there would be a `Token` object which would store the token information that is associated with the particular instace of library. 

One of the benefits of this Token object is it would manage the lifetime of the tokens and could validate if the AccessToken is valid during `refresh`

I do understand your point when you use one instance of the OAuth Library to connect to multiple companies, it could become a problem as the `token` object would always refer to the latest authorized company.

To provide a fix, I have added a new method named `refreshUsingToken(refresh_token)` which accepts the `refresh_token` ( string ) as a param.

For more information please ref to the below:
https://github.com/intuit/oauth-jsclient/blob/master/src/OAuthClient.js#L235

Hope this helps!
