### ISSUE TITLE
[typescript][enhancement]: Remove OAuth1 typing definitions from index.d.ts

### ISSUE THREAD

**Issue by abisalehalliprasan** [intuit/oauth-jsclient#101]
Hacktoberfest is underway right now and we would love for you to contribute  🚀  . More information on #hacktoberfest is [here](https://hacktoberfest.digitalocean.com/)

[Develop-with-Intuit for Hacktoberfest](https://medium.com/intuit-engineering/develop-with-intuit-for-hacktoberfest-2020-8f29b70ff2b4) 

### Problem
Remove unwanted OAuth1 typing definitions from index.d.ts [file](https://github.com/intuit/oauth-jsclient/blob/typescript/index.d.ts) 

### Fix Needed 
Remove all the unnecessary typings : ( interface ) 

- [MigrateParams](https://github.com/intuit/oauth-jsclient/blob/typescript/index.d.ts#L126)
- [GenerateOAuth1SignParams](https://github.com/intuit/oauth-jsclient/blob/typescript/index.d.ts#L130)

### Instructions to use the sample app 

In order to test the typings locally from the sample project, you'll need to link the `intuit-oauth` package with yarn or npm.

```
# Link local intuit-oauth branch with typings support to sample typescript project
yarn link
cd sample/typescript
yarn link intuit-oauth
```

### PR Guidelines 

Kindly follow the below instructions to submit your PR :  

- Fork and clone the repository (`typescript` branch).
- Run `npm install` for dependencies.
- Test all your changes.
- Run `npm test` to execute all specs.

Once ready, please submit a PR to the `typescript` branch [here](https://github.com/intuit/oauth-jsclient/tree/typescript).  
 `Note :` PR's will be merged to the `master` branch once all the testing is completed.

**Comment by luisgregson** [comment]
Hey, i've some experience with type definitions and would like to give this issue a go. Can it be assigned to me please?

**Comment by pradeepb2505** [comment]
#104 Created a PR for this issue a few days back. Please do review it. Thanks.
