### ISSUE TITLE
[typescript][enhancement]: Write a unit test to validate typings definition file

### ISSUE THREAD

**Issue by abisalehalliprasan** [intuit/oauth-jsclient#102]
Hacktoberfest is underway right now and we would love for you to contribute  🚀  . More information on #hacktoberfest is [here](https://hacktoberfest.digitalocean.com/)

[Develop-with-Intuit for Hacktoberfest](https://medium.com/intuit-engineering/develop-with-intuit-for-hacktoberfest-2020-8f29b70ff2b4) 

### Problem
Write a unit test to validate the typings definition file ex: types.test.ts

typings defintion file : `index.d.ts` [file](https://github.com/intuit/oauth-jsclient/blob/typescript/index.d.ts)

### Fix Needed 
Provide a bare minimum `test` for the typings definition file mentioned above. 

### Instructions to use the sample app 

In order to test the typings locally from the sample project, you'll need to link the `intuit-oauth` package with yarn or npm.

```
# Link local intuit-oauth branch with typings support to sample typescript project
yarn link
cd sample/typescript
yarn link intuit-oauth
```

### PR Guidelines 

Kindly follow the below instructions to submit your PR :  

- Fork and clone the repository (`typescript` branch).
- Run `npm install` for dependencies.
- Test all your changes.
- Run `npm test` to execute all specs.

Once ready, please submit a PR to the `typescript` branch [here](https://github.com/intuit/oauth-jsclient/tree/typescript).  
 `Note :` PR's will be merged to the `master` branch once all the testing is completed.

**Comment by VeenaDesai38** [comment]
@abisalehalliprasan I would like to take this up.

**Comment by VeenaDesai38** [comment]
@abisalehalliprasan PR raised for the same https://github.com/intuit/oauth-jsclient/pull/105

**Comment by abisalehalliprasan** [comment]
Thanks @VeenaDesai38 for the contribution 🚀 . Will review the PR soon.

**Comment by VeenaDesai38** [comment]
@abisalehalliprasan Can you please take a look at this PR?
