### ISSUE TITLE
typo '/getCompanyInfo' in app.js

### ISSUE THREAD

**Issue by jwang01** [intuit/oauth-jsclient#11]
var url = oauthClient.environment == 'sandbox' ? oauthClient.environment.sandbox : oauthClient.environment.production ;  

oauthClient should be OAuthClient

var url = oauthClient.environment == 'sandbox' ? OAuthClient.environment.sandbox : OAuthClient.environment.production ;

Apparently, code didn't get tested.

**Comment by crussell42** [comment]
Agreed. I ran into the same issue.

**Comment by abisalehalliprasan** [comment]
Thanks @jwang01  and @crussell42 . A new release is on its way, this should fix it!

**Comment by abisalehalliprasan** [comment]
Fixed with new release [1.1.2](https://github.com/intuit/oauth-jsclient/releases/tag/1.1.2)
