### ISSUE TITLE
PO # shows 'To PRINT' in the form when creating Purchase Order

### ISSUE THREAD

**Issue by mfujinoki** [intuit/oauth-jsclient#111]
When I set PO# and create a Purchase Order, it shows 'TO PRINT' in the form and when I save it in the online form, it saves as a blank.

**Comment by abisalehalliprasan** [comment]
You should be able to create a PO using the `makeAPICall`. Take a look at our API explorer for more details on the request payload and the response 👍 https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/purchaseorder

If you are seeing any issues with the API please consider reaching out to us [here](https://help.developer.intuit.com/s/)
