### ISSUE TITLE
URGENT: Did Intuit change Oauth Flow?

### ISSUE THREAD

**Issue by thekennysong** [intuit/oauth-jsclient#116]
Did Intuit change the Oauth 2.0 process? When trying to auth a client in the oauth window it prompts me to create a new client regardless if client type is QBOA or QBO Plus. This is game breaking for my app. Everything was working fine until this morning.

**Comment by abisalehalliprasan** [comment]
@thekennysong: 
I did check the OAuth flow and I see company selection dropdown ( **as expected** ), shown in the screenshot below : 
![Screen Shot 2021-06-08 at 9 02 01 PM](https://user-images.githubusercontent.com/38014312/121291279-d80b3a80-c89c-11eb-8442-768622e60c63.png)

Could you provide a brief description of the issue you are stating please and if possible attach any screenshot ( as to what you think has changed ? ), I could check with the concerned team and provide an update back to you.

**Comment by thekennysong** [comment]
Hi @abisalehalliprasan it was a known regression bug that lasted a day. Thanks for reaching back out though, I really appreciate it.
