### ISSUE TITLE
Console logging of tokens seems like a bad idea

### ISSUE THREAD

**Issue by stephen-vetbadger** [intuit/oauth-jsclient#13]
Using console.log() is great for debugging but not appropriate for production code. I've put up a PR: https://github.com/intuit/oauth-jsclient/pull/12

**Comment by abisalehalliprasan** [comment]
Apprecite the [PR#12](https://github.com/intuit/oauth-jsclient/pull/12). Will include this for the next release.

**Comment by abisalehalliprasan** [comment]
Fixed with new release [1.1.2](https://github.com/intuit/oauth-jsclient/releases/tag/1.1.2)
