### ISSUE TITLE
invalid_grant error on fresh token

### ISSUE THREAD

**Issue by mzruiz** [intuit/oauth-jsclient#138]
Hola hola,

I've created a new access token successfully. 1m later, I have tried refreshing the token using `.refreshUsingToken(refresh_token)` and am receiving the `invalid_grant` error.

Here's an `intuit_id`: `1-64886bfd-1580fb751f44eb12398d8294`.

A bit more context:

If I perform the following then `refreshResponse` returns back a successful response
```
const oauthClient = new OAuthClient(OAuthConfig);
const authResponse = await oauthClient.createToken(authCode);   
const refreshResponse = await oauthClient.refresh();
console.log('refreshResponse', refreshResponse);
```

But, if I create the token, store in database, and then call our server functions in a different session, I get back `invalid_grant`. 

How come the `refresh()` function does not work when an oauthclient is created in a different session?

- Matt

**Comment by tombensim** [comment]
Hi, I'm also facing the same issue, any update on this?

**Comment by robreiss** [comment]
I treat the refresh_token as a single-use token. When a new access_token is obtained, the refresh_token should be replaced with the one returned alongside the new access token. In a cloud server environment where multiple instances of my program might attempt to access QuickBooks simultaneously, a race condition can occur. To address this, I serialize access to the stored refresh_token using Postgres.

I store the tokens in a table row designated for each company_id and include a column that serves as a lock when refreshing the tokens. This ensures that only one process can refresh the tokens at any given time. While I have not extensively tested this solution in a production setting, it appeared to work effectively during the limited testing conducted before the project I was working on shifted away from QuickBooks.

**Comment by rajeshgupta723** [comment]
Thanks @mzruiz , @tombensim and @robreiss ! Please check the latest npm package: https://www.npmjs.com/package/intuit-oauth/v/4.1.1    closing this issue for now. However, feel free to re-open this if you see any issues. Thanks again!
