### ISSUE TITLE
Open ID connect support

### ISSUE THREAD

**Issue by harshayburadkar** [intuit/oauth-jsclient#14]
Since library claims to support Open ID connect, I was trying to find a method to decode id token but could not find one.

Also, other operations related to id token should be provided, otherwise we will have to end up using two different OAuth2 libraries due to this missing support which probably defeats the purpose of using this library since another library can do all of those functions. I found this missing piece now but since I have already used it in the code I will either have to wait for your release or again refactor to use a different library.

**Comment by harshayburadkar** [comment]
Is it possible to provide at least the id token decode support soon?

**Comment by abisalehalliprasan** [comment]
@harshayburadkar : The helper method to [validateIdToken](https://github.com/intuit/oauth-jsclient/blob/master/src/OAuthClient.js#L515) as per our standard definition is meant to validate if the IDToken is valid. 
Ref : API Reference for [validatingIDToken](https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/openid-connect#step-6-validate-id-token)

Could you please elaborate what information you are looking to get from decoding the IDToken and we can possibly make another helper method to accomodate the changes. 

Thanks.

**Comment by harshayburadkar** [comment]
I was looking for username and/or his email.
I checked the developer documentation again. Apparently, Intuit auth team does not give provide this information in the idToken. If it did it helps to avoid another call to userinfo endpoint to display the username after login. 
I believed it was a common way and was assuming this information is encoded in the payload of idToken. Since it is not the case, I personally do not need a "decode" method anymore and will keep using userinfo call for it.
