### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by knajem** [intuit/oauth-jsclient#15]
I have everything working and the library seems to work well.  I am/was having issues with refreshing/revoking based off of refresh token. 

I kept getting invalid refresh token. I am just testing the refresh function so this is right after I created the token.

I traced it back to this check in token js.

/**
 * Check if there is a valid (not expired) access token
 * @return {boolean}
 */
Token.prototype.isRefreshTokenValid = function() {
    return (this.x_refresh_token_expires_in - this.latency > Date.now());
};

Based off of the comment and what this is doing, seems like two different things. This always seems to evaluate to false for me regardless of when I try to refresh token. Whether its 1 minute after I call create token or 2 hours after I call create token.

I commented out this line in the Oauth file in the validateToken() function.
if(!this.token.isRefreshTokenValid()) throw new Error('The Refresh token is invalid, please Authorize again.');

and was able to successfully revoke and refresh my access token now.

**Comment by abisalehalliprasan** [comment]
Hi @knajem : I just tried to reproduce the issue and I don't see any issue with refreshing the `tokens` using the [refresh()](https://github.com/intuit/oauth-jsclient/blob/master/src/OAuthClient.js#L186). 

[isRefreshTokenValid](https://github.com/intuit/oauth-jsclient/blob/master/src/access-token/Token.js#L120) is important as it checks for the validity of the refreshTokens.

However, below is a small code snippet to show the steps I did : 

```
**
 * Creaste a new oAuth2
 */
var oauthClient = new OAuthClient({
    clientId: 'put your clientID',
    clientSecret: 'put your clientSecret',
    environment: 'production',
    redirectUri: 'put your redirectUri',
    logging: true
});

**
 * Callback function
 */
lets say : 
var callback = 'https://abc.ngrok.io/callback?state=testState&code=L011551462020Rxxxxxxxxxxx2Z3Hk2q2V6B&realmId=19351xxxxxx209'

oauthClient.createToken(callback)
    .then(function(response) {
        console.log('The response in promise is  '+ JSON.stringify(response));
    })
    .then(validateRefresh)
    .catch(function(e) {
        console.log(JSON.stringify(e));
        console.error(e.intuit_tid);
    });

function validateRefresh() {
    oauthClient.refresh()
      .then(function(response){
        console.log('The response is '+ JSON.stringify(response));
      });
}
```

And I was able to verify `refresh` as the two access-tokens were different. Please let me know if there is anything I might have missed. Thanks @knajem

**Comment by knajem** [comment]
Thank you for your quick response @abisalehalliprasan . After adding more console logs this is where I believe my issuers are because of this

**authResponse.token**(_I only copied over the expires stuff for better legibility_)
  token:
   Token {
     expires_in: 1551468150078,
     x_refresh_token_expires_in: 1560190950078,
     latency: 60000 
},


**authResponse.json**(_I only copied over the expires stuff for better legibility_)
   { x_refresh_token_expires_in: 8726400,
     refresh_token: 'L011560190950L5O3n5FKBeTGhrVcOu74AoZjfGtIXQHjb3J7v',
     token_type: 'bearer',
     expires_in: 3600}

From what I can tell the expires in is in seconds from the current date time in the authResponse.json where as the authResponse.token has it as a correct JS Date Timestamp.

I was using authRepsponse.json for my values that get saved into database but it seems I should be using authResponse.token.

**Comment by abisalehalliprasan** [comment]
Spot on @knajem . Library converst the `expires_in` into a current date `timestamp` for some of its helper methods. One such method is the [isRefreshTokenValid()](https://github.com/intuit/oauth-jsclient/blob/master/src/access-token/Token.js#L120). 

Welcome any PR's or suggestions. Cheers !
