### ISSUE TITLE
Is this package compatible with the OIDC changes being released March 1, 2024?

### ISSUE THREAD

**Issue by mgtballison** [intuit/oauth-jsclient#153]
**The Intuit team has announced some upcoming changes to be ready March 1, 2024.** 

Please see the [announcement for those changes here](https://blogs.intuit.com/2023/09/05/changes-to-identity-signature-keys-that-may-impact-your-application/)

Is this package already compatible with the OIDC changes being released March 1, 2024, or will this package no longer work to provide authentication to Quickbooks after this change is released?

Thank you!

**Comment by shweta-intuitdev** [comment]
Hello, this client will continue to work as-is after the OpenID changes go live. No need to make any changes.

**Comment by mgtballison** [comment]
> Hello! This client library will continue to work as-is after the OpenID changes go live. No need to make any changes.

Great, thank you for the info!
