### ISSUE TITLE
Alert from Intuit: "Action Required: Reminder that Intuit changes to identity signature keys may impact your application"

### ISSUE THREAD

**Issue by jay-depot** [intuit/oauth-jsclient#154]
According to an alert email I received from Intuit:

> In the OpenID Connect flow, after making the call to exchange your auth code for an ID token, your app needs to validate the ID token and verify that the signing authority for responses is from Intuit. The [recommended way](https://app.dp.intuit.com/e/er?s=2332625&lid=34&elqTrackId=abce9ade8711403590505fb65b12467f&elq=f63b6b1bb6644b758efa4a61b6bbc019&elqaid=78&elqat=1) to check the signature is to scan through the array of keys at [oauth.platform.intuit.com/op/v1/jwks](http://oauth.platform.intuit.com/op/v1/jwks) for the public key information. The kid value should match the value that was returned in the ID token header.

Is this already handled in this package? If not, will this package be updated for this, or do we have to migrate to a new one?

**Comment by rajeshgupta723** [comment]
Hi Json,

Yes, this is already handled in this package.

Thanks,
Rajesh

**Comment by jay-depot** [comment]
Just for the sake of anyone who might find this issue in a Google search, this deadline has passed, and we've had no issues related to this alert so far.

Thanks!
