### ISSUE TITLE
No prod release in 3 years?

### ISSUE THREAD

**Issue by slawton3** [intuit/oauth-jsclient#156]
There are many problems with this package:
- Many open PRs
- No typescript support
- Popsicle dependency is outdated and broken
- Security issues
- Relying on contributions from OSS community

It was stated that there would be a focus on updating this package in August of 2023. The development branch has been maintained but there hasn't been a prod release since 2021...

I'm sure this minimally impacts Intuit's bottom line, but it would be great for other businesses looking to integrate with the Quickbooks API to be able to authenticate securely with their own Oauth SDK.

**Comment by slawton3** [comment]
For those of you in the same boat, I've managed to successfully integrate with Quickbooks using an integration agnostic Oauth2 Client ([@badgateway/oauth2-client](https://github.com/badgateway/oauth2-client). It has much better documentation and is written in Typescript. 

You can look at the guts of the intuit-oauth package to obtain the relevant URLs and scopes needed to connect.

```
OAuthClient.cacheId = 'cacheID';
OAuthClient.authorizeEndpoint = 'https://appcenter.intuit.com/connect/oauth2';
OAuthClient.tokenEndpoint = 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer';
OAuthClient.revokeEndpoint = 'https://developer.api.intuit.com/v2/oauth2/tokens/revoke';
OAuthClient.userinfo_endpoint_production =
  'https://accounts.platform.intuit.com/v1/openid_connect/userinfo';
OAuthClient.userinfo_endpoint_sandbox =
  'https://sandbox-accounts.platform.intuit.com/v1/openid_connect/userinfo';
OAuthClient.migrate_sandbox = 'https://developer-sandbox.api.intuit.com/v2/oauth2/tokens/migrate';
OAuthClient.migrate_production = 'https://developer.api.intuit.com/v2/oauth2/tokens/migrate';
OAuthClient.environment = {
  sandbox: 'https://sandbox-quickbooks.api.intuit.com/',
  production: 'https://quickbooks.api.intuit.com/',
};
OAuthClient.jwks_uri = 'https://oauth.platform.intuit.com/op/v1/jwks';
OAuthClient.scopes = {
  Accounting: 'com.intuit.quickbooks.accounting',
  Payment: 'com.intuit.quickbooks.payment',
  Payroll: 'com.intuit.quickbooks.payroll',
  TimeTracking: 'com.intuit.quickbooks.payroll.timetracking',
  Benefits: 'com.intuit.quickbooks.payroll.benefits',
  Profile: 'profile',
  Email: 'email',
  Phone: 'phone',
  Address: 'address',
  OpenId: 'openid',
  Intuit_name: 'intuit_name',
};
```
You can use the fetchWrapper to automatically include the token in the authorization header for requests to the Quickbooks API.

**Comment by rajeshgupta723** [comment]
As release 4.1.0 was completed, closing this issue
