### ISSUE TITLE
Error revoking token, this.token.refreshToken is not a function

### ISSUE THREAD

**Issue by jt274** [intuit/oauth-jsclient#16]
I've already retrieved tokens and am able to successfully communicate with the API using them. The tokens are stored in a database. I am unable to call the revoke function to revoke the tokens though, as I get the following error: **TypeError: this.token.refreshToken is not a function**

The tokens are retrieved from the database and the token revoke code is:

oauthClient.revoke()
          .then((authResponse) => {
            console.log('Token revoked: ' + JSON.stringify(authResponse.json()));
          }).catch((e) => {
            console.error('Error revoking token: ' + e);
          });

I am setting the token to the current client instance:

oauthClient.token = {
      "token_type": "bearer",
      "expires_in": 3600,
      "refresh_token": "<refresh_token>",
      "x_refresh_token_expires_in": 15552000,
      "access_token": "<access_token>"
    };

I get the same error if simply passing the refresh token or access token to the revoke function - none of the below work with the token or refresh token:

`oauthClient.revoke({refresh_token})

oauthClient.revoke(refresh_token)

oauthClient.revoke({"token": refresh_token})`

In the library OAuthClient.js line 638 I see:

`if(!this.token.refreshToken()) throw new Error('The Refresh token is missing');`

Am I passing the wrong info? Strange it says it is not a function. I'm on the latest version 1.1.2.

**Comment by abisalehalliprasan** [comment]
@jt274 : I tried all the three options and the `revoke` works perfectly fine : 
`oauthClient.revoke({refresh_token})`
`oauthClient.revoke(refresh_token)`
`oauthClient.revoke({"token": refresh_token})`

FYI : Passing the parameters to this function is optiona as you are already setting the token instance above. 

Also, setting the token looks incorrect with what you are doing. Please refer to : [README -> Set Tokens](https://github.com/intuit/oauth-jsclient#set-the-token-)

**Comment by jt274** [comment]
I've read that a few times, but when I do this:

var oauthClient = new OAuthClient({
  clientId: API_KEY,
  clientSecret: API_SECRET,
  environment: ENVIRONMENT,
  redirectUri: REDIRECT_URI,
});

//Other code doing things

oauthClient.token = new Token(authToken);

I get **ReferenceError: Token is not defined**

**Comment by abisalehalliprasan** [comment]
@jt274 : I agree with you. We could perhaps expose a helper method to `setToken` using the `oauthClien`t instance. 

I have implemented this change and will be testing some new changes that are going into the library. Please expect a release by Monday or Tuesday at the earliest. 

Apologize for the inconvenience caused.

**Comment by jt274** [comment]
Thanks. Just wanted to make sure I wasn't missing something.

**Comment by abisalehalliprasan** [comment]
@jt274 : Issue has been fixed in the new release [1.1.3](https://github.com/intuit/oauth-jsclient/releases/tag/1.1.3)

**Comment by jt274** [comment]
@abisalehalliprasan I am getting the same error. Perhaps you could walk me through the correct way to revoke the token when the token information is stored in a database? This is what I currently have, gives ReferenceError: Token is not defined, v1.1.3.

const OAuthClient = require('intuit-oauth');

var oauthClient = new OAuthClient({
  clientId: API_KEY,
  clientSecret: API_SECRET,
  environment: ENVIRONMENT,
  redirectUri: REDIRECT_URI,
});

//Token is retrieved from the database

var authToken = {
      "token_type": "bearer",
      "expires_in": 3600,
      "refresh_token": token.refresh_token,
      "x_refresh_token_expires_in": 8726400,
      "access_token": token.access_token,
      "id_token": token.id_token
    };

oauthClient.token = new Token(authToken);

oauthClient.revoke()
          .then((authResponse) => {
            console.log('Token revoked: ' + JSON.stringify(authResponse.json()));
          }).catch((e) => {
            console.error('Error revoking token: ' + e);
          });

**Comment by jt274** [comment]
Was able to get it working with 1.1.3 using `oauthClient.setToken(authToken);`

It appears though that it tries to first check if the refresh token is valid (not expired), and if it is expired it throws an error. Why should that matter? It doesn't seem right to have to refresh the token before revoking it if it's expired.

Line 640 OAuthClient.js:

`if(!this.token.isRefreshTokenValid()) throw new Error('The Refresh token is invalid, please Authorize again.');`

Called by `this.validateToken();` on line 297 in the revoke method.

Thanks!

**Comment by abisalehalliprasan** [comment]
@jt274 
I completely agree with the statement : 
`It doesn't seem right to have to refresh the token before revoking it if it's expired.`

However, if the refresh Token is expired and if you do pass the same `refresh Token(expired)` or `access Token(expired)` to revoke your tokens, the API would return a : 

400 Bad Request 

So, the revoke() method does a validation to check if atleast the refresh Token is valid.

**Comment by jt274** [comment]
@abisalehalliprasan Understood. If the refresh token is expired, does it need to be revoked? The company is essentially already disconnected. I suppose that's something that could be handled by an app.

**Comment by abisalehalliprasan** [comment]
@jt274 : Expired tokens are already revoked from `Intuit`. Your app would need to handle that based on the activity and lifetime of the company ( as in the token ). 

I am working on a next release which includes `events`. The SDK would emit events which app can listen to track the progress of the tokens during its entirety. Next release would have it.

**Comment by jt274** [comment]
Sounds great, thanks!
