### ISSUE TITLE
4.1.0 throws TypeError: Converting Circular structure to JSON

### ISSUE THREAD

**Issue by amadeogallardo** [intuit/oauth-jsclient#161]
The following error is thrown by the latest version of the OAuth Client:

> TypeError: Converting circular structure to JSON
>   --> starting at object with constructor 'ClientRequest'
>   |     property 'res' -> object with constructor 'IncomingMessage'
>         --- property 'req' closes the circle
>         at JSON.stringify (<anonymous>)
>         intuit-oauth\src\OAuthClient.js:405:66

**Comment by ysageev** [comment]
Same problem.  Now I'm having trouble reverting as well to 4.0.0.

**Comment by rajeshgupta723** [comment]
Thank you @amadeogallardo and @ysageev  , I've created a new branch from the master, called release-4.1.1 and raised this PR: https://github.com/intuit/oauth-jsclient/pull/160

Please verify if this PR fixes the issue. If all looks good, will merge this PR into master later this week. Thanks

**Comment by amadeogallardo** [comment]
Thank you @rajeshgupta723, I will wait for the patch release to be tagged and then upgrade the dependency to confirm the fix.

**Comment by ysageev** [comment]
Yes, a tagged patch release would be more convenient for me as well.

**Comment by rajeshgupta723** [comment]
Thank you @amadeogallardo and @ysageev -- a patch release 4.1.1 has been created. https://github.com/intuit/oauth-jsclient/releases/tag/4.1.1

**Comment by laurentjacob** [comment]
@rajeshgupta723 Can you publish a new version on npm as well? Latest is still 4.1.0

**Comment by ysageev** [comment]
Thank you @rajeshgupta723.  I'm not sure how to build the 4.1.1 module.  I don't see a build script.

Can you explain how to build and test the 4.1.1 module in our own projects? Or as @laurentjacob said, publish it to npm?

**Comment by rajeshgupta723** [comment]
Thank you @laurentjacob and @ysageev , appreciate your support! latest npm has been relased: https://www.npmjs.com/package/intuit-oauth/v/4.1.1

**Comment by ianberryman** [comment]
Hi, I'm seeing the same error in 4.1.1 when calling `refreshUsingToken`. I only looked briefly but it appears that it might be an issue anytime `JSON.stringify(authResponse, ...)` is called.
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle
    at JSON.stringify (<anonymous>)
    at ...\node_modules\intuit-oauth\src\OAuthClient.js:274:14

```
