### ISSUE TITLE
4.1.1 throws TypeError: Converting Circular structure to JSON

### ISSUE THREAD

**Issue by ianberryman** [intuit/oauth-jsclient#164]
Hi, I'm seeing an error in 4.1.1 when calling refreshUsingToken. I only looked briefly but it appears that it might be an issue anytime JSON.stringify(authResponse, ...) is called. Related to https://github.com/intuit/oauth-jsclient/issues/161

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle
    at JSON.stringify (<anonymous>)
    at ...\node_modules\intuit-oauth\src\OAuthClient.js:274:14

**Comment by ianberryman** [comment]
I have a production use case for this so I'm going to submit a PR

**Comment by rajeshgupta723** [comment]
Thanks @ianberryman , I've merged your PR into master and created this new branch: 
https://github.com/intuit/oauth-jsclient/tree/release-4.1.2

Please test your changes and overall there. Will be  using this branch for the next release 4.1.2 later

**Comment by ianberryman** [comment]
Thank you

**Comment by EthanDavis** [comment]
I have this same issue. Are there plans to cut a 4.1.2 release soon?

**Comment by rajeshgupta723** [comment]
Hi @EthanDavis please test your use case in this branch [release-4.1.2 ](https://github.com/intuit/oauth-jsclient/tree/release-4.1.2) and confirm everything looks good there. Yes, we will soon release this 4.1.2 branch. Thanks

**Comment by rajeshgupta723** [comment]
Hi @BogdanPekar @ianberryman @EthanDavis , FYI - Release 4.1.2 has been pushed out, please checkout at https://github.com/intuit/oauth-jsclient/releases 

closing this issue. please feel free to reopen this if you still see any issues. Thanks

**Comment by AliHydr** [comment]
Hi @rajeshgupta723 I'm still facing the same issue

**Comment by ianberryman** [comment]
@AliHydr Are you using version 4.1.2? I've used both the release branch and the new npm version without issue.
