### ISSUE TITLE
createToken not returning AuthResponse object (ie. `getJson()` is not a function)

### ISSUE THREAD

**Issue by johne** [intuit/oauth-jsclient#167]
in `createToken` the response from `getTokenRequest` is an `AuthResponse` but this line:
```
      const { response, ...authResponse } = res.json ? res : null;
```
turns it into an object which looses all the prototype functions.

according to the documentation here: https://github.com/intuit/oauth-jsclient?tab=readme-ov-file#step-2 you should be able to call `getJson` on the result of `createToken` but since it is plain object, `getJson` is not a function.

a workaround is to just use `.json` to get the json directly.

**Comment by rajeshgupta723** [comment]
Hi @johne, the workaround and updated documentation file has been pushed to this branch: https://github.com/intuit/oauth-jsclient/tree/release-4.1.2

**Comment by rajeshgupta723** [comment]
Hi @johne, Release 4.1.2 has been pushed out, please checkout at https://github.com/intuit/oauth-jsclient/releases 

closing this issue. please feel free to reopen this if you still see any issues. Thanks

**Comment by junder31** [comment]
The 4.1.2 artifact on NPM does not appear to contain these latest changes.  I'm still not able to successfully make requests with response types other than JSON.
