### ISSUE TITLE
Error in revoke token :- Error: Response has an Error

### ISSUE THREAD

**Issue by ruchikam** [intuit/oauth-jsclient#19]
I had got an instance of oauthclient after connection using 
  oauthClient = new OAuthClient({
                  clientId: quickbook_token.clientId,
                  clientSecret: quickbook_token.clientSecret,
                  environment: quickbook_token.environment,
                  redirectUri: quickbook_token.redirectUri,
                  token:quickbook_token.token
              });

and create a tokenJson :
let tokenJSON = {
                "token_type": quickbook_token.token.token_type,
                "expires_in": quickbook_token.token.expires_in,
                "refresh_token":quickbook_token.token.refresh_token,
                "x_refresh_token_expires_in":quickbook_token.token.x_refresh_token_expires_in,
                "access_token":quickbook_token.token.access_token
              }

using the previously connection token saved in database
                oauthClient.revoke({token:tokenJSON})
                       .then(function(authResponse) {
                         console.log('Tokens revoked : ' + JSON.stringify(authResponse.json()));
                       })
                       .catch(function(e) {
                         console.error("The error message is :"+e.originalMessage);
                         console.error(e.intuit_tid);
                         handleResponse.handleError(res, e, ' Error in revoking token'+e);
                       });

I am getting the error. I had tried passing only refresh_token also. and validate token before sending

**Comment by abisalehalliprasan** [comment]
@ruchikam : 

Just pass the `tokenJson` object as shown below : 
```
oauthClient.revoke(tokenJSON)
.then(function(authResponse) {
console.log('Tokens revoked : ' + JSON.stringify(authResponse.json()));
})
.catch(function(e) {
console.error("The error message is :"+e.originalMessage);
console.error(e.intuit_tid);
handleResponse.handleError(res, e, ' Error in revoking token'+e);
});
```
Refer to the README under [Revoke Tokens](https://github.com/intuit/oauth-jsclient#revoke-access_token) if you have any doubts.

**Comment by ruchikam** [comment]
I had passed the json token but got error: cannot read property revoke of null

oauthClient.revoke(tokenJSON)
.then(function(authResponse) {
console.log('Tokens revoked : ' + JSON.stringify(authResponse.json()));
})
.catch(function(e) {
console.error("The error message is :"+e.originalMessage);
console.error(e.intuit_tid);
handleResponse.handleError(res, e, ' Error in revoking token'+e);
});

oauthClient is null since I am not able to get the connection instance after initial creation and connection for further processing.

**Comment by ruchikam** [comment]
When I logged the error I get the following response:

2019-04-17T06:44:50.773Z error: Refresh Token () threw an exception : {
  "authResponse": {
    "token": {
      "realmId": "123146326718089",
      "token_type": "bearer",
      "access_token": "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..AEJkzSttdjmusGqJuQK9GA.ixGrn2VPldDuNog_ekOxrTNme_g5aej1kS_7a95RCqNO70YrxqkkVSSGLZ7E--6rmxQx3knFeQKHLrteo-pTg-datTxMCpFmssV3W2vALhyVmWkiPHVF9BY9BW2moqI4uzuiYJAuiaT6HNsFEkNypBnG3kxpMq83L1J7eTxeRFvS-0vS2g50pCqUQhyoSXu1Pn-jO2aUeZvMaLymoGP_vKQGjzm8TlqbIZr6Ard0OFsWjlUYgIeAkpXIIW64R69FA6aXjY7BPFnST8kVE_rxWwD7fJCAWzDUhaROIqicel1IJDU0Y0nNcpGnViufQWCTq3ingRbeGYJuKdHY7mN6NRLGm3i4QLh2XweSVDQpk63Kfhul8z_n-8wOPM04tDM8y3wdGBn-GsV2G0kcVn0XYXhgWv96bH_fTCVXQk93E3YUmViMhFZzGZ0p8rki-CRQF260bzP0Hy5nLkJExrG-XiW4ujGUWGWgCJfmG8B1IFpIzXO4lE3TmWyM3BI7bitvQmERBAo0MqgsvrARNx55z8huUy4qHqvniGel4h-QCavncsqHRK5xzp99CgM2gSS-hyruXnPqpZhmHacPw2foJDdYG3QRHNqpLWu45F9hBwSQLBVyoKSIvOYqamzaTq63IhQD1iE6z72gNG2Q9P4aD85GjJAXUjvXXDQk0aGI6vIsyZ_iz2THZ-3OcdHGYB8JTQmP-vymKjUTJK33snrCrkSBAOVLJnR-8kRAXyFUNHPpjYvOIXuQc4S6mrmhlLtM3J3-i8cXGoqEfjHygMa9jOBnILyp5iPH1EKbbLwmOzY.XYLUAeSvEVyYJQQ8edSr-Q",
      "refresh_token": "Q011564208104zvN3MDHpTIjAXnqab13s77hMEQ1E7WdnDUdtC",
      "expires_in": 1555485304659,
      "x_refresh_token_expires_in": 1564208104659,
      "id_token": "eyJraWQiOiJPUElDUFJEMDkxODIwMTQiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2OGZiNzdlYy0yNWExLTQ2MmEtOWI0NS1iY2FjMjIxYmVlOGUiLCJhdWQiOlsiUTBmeHBKV3FPYzh5TThpSjlDMG1Kc1RQQ1hDZm1VZTV2VU1GeGNFQjg0eFpRQ1Y3MEUiXSwicmVhbG1pZCI6IjEyMzE0NjMyNjcxODA4OSIsImF1dGhfdGltZSI6MTU1NTQ4MTY4MCwiaXNzIjoiaHR0cHM6XC9cL29hdXRoLnBsYXRmb3JtLmludHVpdC5jb21cL29wXC92MSIsImV4cCI6MTU1NTQ4NTMwNCwiaWF0IjoxNTU1NDgxNzA0fQ.nue8HzR_iZs6fp5Jmlkmovuk_vNWLpwIppHHDB7xyFwai9HYLs06gIs0qBo3j5bpX1_G0PYlICYv07lioUrxKKdjUSx0FcMv2bMuCDjGL7Sgj4wGsUyvfdeavEpftr0BZSqBYSK4BCGhN8C90PB-lHlB1XuTsV6Gy9bh0vb7m6w",
      "latency": 60000
    },
    "response": {
      "url": "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
      "headers": {
        "content-type": "application/json;charset=utf-8",
        "content-length": "25",
        "connection": "close",
        "server": "nginx",
        "date": "Wed, 17 Apr 2019 06:44:50 GMT",
        "strict-transport-security": "max-age=15552000",
        "intuit_tid": "732f9b22-dacb-3a44-aadc-daf099298890",
        "cache-control": "no-cache, no-store",
        "pragma": "no-cache"
      },
      "body": "{\"error\":\"invalid_grant\"}",
      "status": 400,
      "statusText": "Bad Request"
    },
    "body": "{\"error\":\"invalid_grant\"}",
    "json": {
      "error": "invalid_grant"
    },
    "intuit_tid": "732f9b22-dacb-3a44-aadc-daf099298890"
  },
  "originalMessage": "Response has an Error",
  "error": "invalid_grant",
  "error_description": "",
  "intuit_tid": "732f9b22-dacb-3a44-aadc-daf099298890"
}

**Comment by ruchikam** [comment]
I just want to know how to get oauthClient instance once we had connected

**Comment by abisalehalliprasan** [comment]
Please do not disclose token information on public forums. I have masked the above information for now. 

If you have declared oauthClient as a `Global Variable` you should be able to use it inside any scope within your program. Could you please paste the entire code ( _please mask any sensitive data_ )so that we could know why oauthClient instace is recognized as `undefined` ? 

You can also email our developer suppoprt here : https://help.developer.intuit.com/s/contactsupport
