### ISSUE TITLE
Error : Response has an Error

### ISSUE THREAD

**Issue by Vaatyk** [intuit/oauth-jsclient#2]
Hi I wanted to use your node.js version 8 script to connect to Quickbooks using Oauth2 and so far so good except whenever I create the realmID and the AcessToken I keep getting in my terminal (I'm on MAC so unix/bash terminal) **Error : Respons has an Error** From the json error object. 

In details : 

 Response {
        Url: [Object],
        rawHeaders: [Array],
        body: '{"warnings":null,"intuitObject":null,"fault":{"error":[{"message":"message=AuthorizationFailed; errorCode=003100; statusCode=403","detail":null,"code":"3100","element":null}],"type":"SERVICE"},"report":null,"queryResponse":null,"batchItemResponse":[],"attachableResponse":[],"syncErrorResponse":null,"requestId":null,"time":1543012192555,"status":null,"cdcresponse":[]}',
        status: 403,
        statusText: 'Forbidden' },
     body: '{"warnings":null,"intuitObject":null,"fault":{"error":[{"message":"message=AuthorizationFailed; errorCode=003100; statusCode=403","detail":null,"code":"3100","element":null}],"type":"SERVICE"},"report":null,"queryResponse":null,"batchItemResponse":[],"attachableResponse":[],"syncErrorResponse":null,"requestId":null,"time":1543012192555,"status":null,"cdcresponse":[]}',

**Comment by Vaatyk** [comment]
I'm getting forbidden 403 errors but my login informations are good.

**Comment by abisalehalliprasan** [comment]
@Vaatyk ,

Could you check if you are using the correct base url. Looks like using the OAuth-Client you are getting the tokens. And to make any API call, you are getting this error. 

For **Sandbox** companies you need to use sandbox base url : 
https://sandbox-quickbooks.api.intuit.com/v3/company/ 

For **Production** you need to use production base url : https://quickbooks.api.intuit.com/v3/company/

You can take a look at the sample app [here](https://github.com/intuit/oauth-jsclient/blob/master/sample/app.js#L120)

**Comment by Vaatyk** [comment]
Hi. Thank you for your reply, I checked my apiCall.php and callback.php and
changed the baseUrl in the DataService object with the sandbox link
you provided and I still get the same error.

It's making me go crazy haha.

**Comment by Vaatyk** [comment]
Oh I thought this was the php version sorry have a nice day

**Comment by abisalehalliprasan** [comment]
Not a problem. Have a good day !

**Comment by abisalehalliprasan** [comment]
Not a problem . Happy coding !
