### ISSUE TITLE
Timestamps are not computed in the constructor. Validation checks fail.

### ISSUE THREAD

**Issue by ryan-sandy** [intuit/oauth-jsclient#21]
As referenced in [issue 7](https://github.com/intuit/oauth-jsclient/issues/7), the timestamps are incorrectly computed if you use the `setToken()` method versus the constructor.

The constructor treats the expiry information as a timestamp versus `setToken()` which computes a timestamp off of `Date.now()`.

This causes the validation checks to behave differently depending on how you created the token.

**Comment by abisalehalliprasan** [comment]
Thanks, @ryan-sandy for the PR - [#21](https://github.com/intuit/oauth-jsclient/pull/20). I did get a chance to look at the files you have changed. They look good. 

Just need to test the changes once before merging the PR. Will provide an update soon here.

Thanks for your time and effort!

**Comment by abisalehalliprasan** [comment]
Merged #20
