### ISSUE TITLE
Support for POST Request create/update

### ISSUE THREAD

**Issue by vikas-ss** [intuit/oauth-jsclient#23]
Is there any support for making POST request create/update entity? Intuit-outh module provides makeAPICall method which can be used to get employee, customer list from Intuit account, method "GET" is hardcoded in that, there is no way we can pass method into this.

Are you planning to provide POST create/update?

**Comment by abisalehalliprasan** [comment]
@vikas-ss : We are working on releasing an Official SDK to support NodeJS developers soon. But in the meantime you can use the community supported SDK to make API calls : 

[Community Supported Node SDK](https://github.com/mcohen01/node-quickbooks)

You can find the community supported OAuth2Example [here](https://github.com/mcohen01/node-quickbooks/tree/master/oauth2example)

**Comment by vikas-ss** [comment]
Okay Thanks. Yeah I had seen community supported SDK already.

**Comment by desaias** [comment]
@abisalehalliprasan Is there any ETA for the official SDK?
