### ISSUE TITLE
PassportJS

### ISSUE THREAD

**Issue by YasharF** [intuit/oauth-jsclient#25]
Would you be able to provide some guidance on integration with PassportJS?

**Comment by anilkumarbp** [comment]
@YasharF : I have not used [PassportJS](http://www.passportjs.org/) in the past. But going through their documentation, it seems like a middleware which is used to authenticate requests in node applications. Our [client](https://github.com/intuit/oauth-jsclient) is just doing that.

I am not sure why you would want to integrate with `PassportJS`. Help me fill in on this and we could take a look at it. Thanks !

**Comment by YasharF** [comment]
Using your middleware is a one-off implementation.  PassportJS is a more standardized way.  Many people would not use one-off solutions, especially if there is a need to integrate with multiple services.

Anyway, I ended up doing the integration of intuit/QuickBooks with PassportJS using the generic OAuth 2.0 plugin for passport js: https://github.com/sahat/hackathon-starter/commit/285b6b170d029322b0b000f056c2ce9331728398

**Comment by abisalehalliprasan** [comment]
Looking at the starter code you have provided [here](https://github.com/sahat/hackathon-starter/commit/285b6b170d029322b0b000f056c2ce9331728398) seems like exchanging the `authCode` for access/refresh tokens is not handled or may be I have missed something ?!

But this is a great value addition to developers who are integrating multiple services. I will send in a PR once I get past this. Thanks @YasharF

**Comment by YasharF** [comment]
You are correct, handling the refresh token is an issue with pretty much all of the oAuth providers that hackathon-starter has integration with, and we are working on fixing it:
https://github.com/sahat/hackathon-starter/issues/977
https://github.com/sahat/hackathon-starter/pull/976

**Comment by abisalehalliprasan** [comment]
Alrighty. Good Stuff @YasharF  

The excited me wanted to try out the `QuickBooks` implementation in your sample. However, I did not see an option to SignIn with QuickBooks when I visit the page http://localhost:8080/login after deploying `app.js`

Also, do I need to be logged into the website to invoke Sign in with QuickBooks?
https://cdn1.imggmi.com/uploads/2019/7/11/f5782c9769d74a08d37ca5e74cd75c70-full.png
