### ISSUE TITLE
isAccessTokenValid() is true after calling revoke() 

### ISSUE THREAD

**Issue by matbalazsi** [intuit/oauth-jsclient#28]
If I understand correctly, I would expect that isAccessTokenValid() to return false after calling revoke(). Here is my simplified test:

_From an authorized state:_

`let initialState = oauthClient.isAccessTokenValid()`

**yields initialState = true**

`let response  = await  oauthClient.revoke();`

`let finalState = oauthClient.isAccessTokenValid()`

**yields finalState = true, expected false**

**Comment by abisalehalliprasan** [comment]
Clearing the token information has not been handled with the previous release. Will be fixing that in the new release. Thanks @matbalazsi.

**Comment by abisalehalliprasan** [comment]
@matbalazsi : This is handled in the new release [1.4.0](https://github.com/intuit/oauth-jsclient/tree/1.4.0)

**Comment by matbalazsi** [comment]
Thanks!
