### ISSUE TITLE
Unable to create tokens from access code

### ISSUE THREAD

**Issue by skyarkitekten** [intuit/oauth-jsclient#3]
I am using `intuit-oauth` package version 1.0.3 inside of a React application. 

I am able to initiate the OAuth flow and receive the _code_ and the _realmId_ successfully on the callback route.

Then, I pass that URI into the client's `createToken` method to create the access and refresh tokens and receive the following errors:

* Refused to set unsafe header "User-Agent"
* Access to XMLHttpRequest at 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
* PopsicleError: Unable to connect to "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer"

Other OAuth flows (Auth0, Google) are working successfully inside the React app.

**Comment by skyarkitekten** [comment]
This seems to be an issue with client flows using OAuth2 implicit grants. In the developer forums, it is said that Intuit only supports server-side access. 

Can someone on the dev team confirm?

**Comment by abisalehalliprasan** [comment]
Hi @skyarkitekten ,

We only support OAuth2.0 Authorization Flow at the moment which is supported only on the server side. 

We are planning to support `OAuth2 implicit grant` in the near future.

**Comment by skyarkitekten** [comment]
Thanks, @abisalehalliprasan.

I am glad to hear that implicit grant is on your roadmap. In the meantime, I will introduce a server into our solution.

**Comment by pbro123** [comment]
Hi @abisalehalliprasan ,

I've just come across the same issue - was OAuth2 implicit grant support ever implemented?

Many thanks
