### ISSUE TITLE
Extend the library to support TypeScript 

### ISSUE THREAD

**Issue by abisalehalliprasan** [intuit/oauth-jsclient#33]
Goal : 
To be able to support  `typescript` community

Ref : 
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gapi.client.oauth2
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/simple-oauth2

**Comment by qjd2413** [comment]
seems interesting; could you assign this to me?

**Comment by spencerwi** [comment]
I think I can take a crack at it.

There are two ways to handle Typescript support:

1. Include declaration file(s) in your own repo, and point the `types` property of `package.json` at the "root" type declaration file (or just name it `index.d.ts`). This makes everything "just work" out of the box for devs using Typescript, as the Typescript compiler will know where to find the type definition files when Typescript devs do `const OAuthClient = require('intuit-oauth');`

2. Create declaration files, and submit them to DefinitelyTyped (the repo you linked to). In this case, Typescript developers will need to install a separate dev dependency from the `@types` namespace that corresponds to your library:

```
$ npm install --save-dev @types/intuit-oauth`
```

**Comment by abisalehalliprasan** [comment]
@qjd2413 : Awesome. Just did that 👨‍💻. Appreciate that @qjd2413

**Comment by spencerwi** [comment]
Oh, shoot, I'm just a tiny bit late. womp womp, I'll find another issue.

**Comment by abisalehalliprasan** [comment]
@spencerwi: There might be more. I will keep you posted. Thank you.

**Comment by 29er** [comment]
im kinda surprised you dont have these yet. anything on the horizon ?

**Comment by abisalehalliprasan** [comment]
@29er : We will be releasing the typescript version soon. Thanks.

**Comment by jponc** [comment]
@abisalehalliprasan did the TS types pushed through?

**Comment by abisalehalliprasan** [comment]
@jponc : We have a `typescript` branch but the code is not Production-ready yet. 
Ref : oauth-jsclient [typescript](https://github.com/intuit/oauth-jsclient/tree/typescript)

I cannot provide exact timelines on the release at the moment. But you are free to look at the sample example [here](https://github.com/intuit/oauth-jsclient/tree/typescript/sample/typescript) if it helps.

**Comment by jponc** [comment]
No worries, thanks mate 👍

**Comment by salvadorbarb1** [comment]
im kinda surprised you dont have these yet. anything on the horizon ?

**Comment by ryannewton** [comment]
Is this published?

I just tried running `npm install --save-dev @types/intuit-oauth` and I can't tell if I'm missing something or if it's still being developed.

**Comment by ryannewton** [comment]
@abisalehalliprasan
Could you provide an update on this?

 I'm just jumping into using `intuit-oauth` and am using Typescript. It'd be nice to have confirmation if I'm missing something or if this project got shelved.

**Comment by abisalehalliprasan** [comment]
Hi @ryannewton : 
There a few things which need to be tested before we release the typescript version. We will try to prioritize a release very soon. Thank you for your understanding!

**Comment by jesuschris** [comment]
Hello! Any pre-release options? :)

**Comment by jesuschris** [comment]
Hello @abisalehalliprasan! Just checking in :dancers:

**Comment by zenininja** [comment]
Hi, What is the status of typescript type definition ? Could you please provide it ?

**Comment by lsacco-nutreense** [comment]
Hello @abisalehalliprasan...It's been almost 6 months since your last post and I don't see anything posted on NPM in this regard. This would be a big help for us. Thanks.

**Comment by AshMartian** [comment]
Quick work around for Typescript users.

- Create a new folder in root of project `types`
- New folder inside that called `intuit-oauth`
- Reference this folder in `tsconfig.json`
```json
...
        "types": [
            "intuit-oauth",
        ],
        "typeRoots": [ "./types", "./node_modules/@types"],
...
```
- New file inside `intuit-oauth` called `index.d.ts`
- I copied the type definitions from [the typescript branch](https://github.com/intuit/oauth-jsclient/blob/typescript/index.d.ts) but was full of errors. Cleaned it up and it's eslint happy in [this gist](https://gist.github.com/AshMartian/6eabf12bfc6cbbc7a58d672d465ae2b0)

This has not been fully tested, but seems to work. Someone should test this and make a PR as Typescript support here seems essential.

**Comment by sdegutis** [comment]
Why is this closed if it's not released?

**Comment by GuiSim** [comment]
@abisalehalliprasan can you comment on the current state of type definitions for TypeScript?

**Comment by bluefire2121** [comment]
Bump

**Comment by juanjalvarez** [comment]
> Quick work around for Typescript users.
> 
> * Create a new folder in root of project `types`
> * New folder inside that called `intuit-oauth`
> * Reference this folder in `tsconfig.json`
> 
> ```json
> ...
>         "types": [
>             "intuit-oauth",
>         ],
>         "typeRoots": [ "./types", "./node_modules/@types"],
> ...
> ```
> 
> * New file inside `intuit-oauth` called `index.d.ts`
> * I copied the type definitions from [the typescript branch](https://github.com/intuit/oauth-jsclient/blob/typescript/index.d.ts) but was full of errors. Cleaned it up and it's eslint happy in [this gist](https://gist.github.com/AshMartian/6eabf12bfc6cbbc7a58d672d465ae2b0)
> 
> This has not been fully tested, but seems to work. Someone should test this and make a PR as Typescript support here seems essential.

This worked perfectly for me, thank you!

**Comment by tedyme** [comment]
Really guys? Three+ years? That's totally not serious!

**Comment by flare-autobots** [comment]
@juanjalvarez does it work for production? I am having an issue.

```
2023-03-24T18:21:19.164Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module './development.js'\nRequire stack:\n- /var/task/node_modules/@dabh/diagnostics/node/index.js\n- /var/task/node_modules/winston/lib/winston/exception-handler.js\n- /var/task/node_modules/winston/lib/winston/logger.js\n- /var/task/node_modules/winston/lib/winston/create-logger.js\n- /var/task/node_modules/winston/lib/winston.js\n- /var/task/node_modules/intuit-oauth/src/OAuthClient.js\n- /var/task/src/functions/quickBooks/oauth/handler.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module './development.js'",
        "Require stack:",
        "- /var/task/node_modules/@dabh/diagnostics/node/index.js",
        "- /var/task/node_modules/winston/lib/winston/exception-handler.js",
        "- /var/task/node_modules/winston/lib/winston/logger.js",
        "- /var/task/node_modules/winston/lib/winston/create-logger.js",
        "- /var/task/node_modules/winston/lib/winston.js",
        "- /var/task/node_modules/intuit-oauth/src/OAuthClient.js",
        "- /var/task/src/functions/quickBooks/oauth/handler.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:996:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1031:21)",
        "    at async start (file:///var/runtime/index.mjs:1194:23)",
        "    at async file:///var/runtime/index.mjs:1200:1"
    ]
}
```

**Comment by zahinz** [comment]
Hello from Nov 2023...

**Comment by yannickcare** [comment]
26 Dec 2023 and this is still not implemented?

**Comment by yannickcare** [comment]
> Quick work around for Typescript users.
> 
> * Create a new folder in root of project `types`
> * New folder inside that called `intuit-oauth`
> * Reference this folder in `tsconfig.json`
> 
> ```json
> ...
>         "types": [
>             "intuit-oauth",
>         ],
>         "typeRoots": [ "./types", "./node_modules/@types"],
> ...
> ```
> 
> * New file inside `intuit-oauth` called `index.d.ts`
> * I copied the type definitions from [the typescript branch](https://github.com/intuit/oauth-jsclient/blob/typescript/index.d.ts) but was full of errors. Cleaned it up and it's eslint happy in [this gist](https://gist.github.com/AshMartian/6eabf12bfc6cbbc7a58d672d465ae2b0)
> 
> This has not been fully tested, but seems to work. Someone should test this and make a PR as Typescript support here seems essential.

I did this, in nest.js, had to put it inside tsconfig.app.json:


`{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
    "types": ["node", "intuit-oauth"],
    "typeRoots": ["./types", "./node_modules/@types"],
    "emitDecoratorMetadata": true,
    "target": "es2021"
  },
  "exclude": ["jest.config.ts", "src/**/*.spec.ts", "src/**/*.test.ts"],
  "include": ["src/**/*.ts", "assets/**/*"]
}
`

but still getting :
[Nest] 57800  - 2023-12-26, 8:54:22 a.m.   ERROR [ExceptionHandler] intuit_oauth_1.OAuthClient is not a constructor

am I missing something?

**Comment by vinu-ablabs** [comment]
Hello from 2024

**Comment by egervari** [comment]
It's essential to include TypeScript support. TypeScript, introduced in 2012 and further popularized by Angular in 2016, has become a cornerstone of modern development. With frameworks like NestJS leveraging its capabilities since 2017, it's evident that TypeScript is integral to contemporary programming practices. Given the significant financial transactions your customers conduct, the absence of TypeScript support seems unwarranted. It's high time for this support to be officially integrated.

**Comment by AliHydr** [comment]
I don't think they will introduce it anytime soon :(

**Comment by ananay** [comment]
lol, this isn't happening folks. it's time for us to step in

**Comment by kuang** [comment]
What's the status on this? @IntuitDeveloperRelations

**Comment by jjuli93** [comment]
Why is this closed? no plan to releasing it?

**Comment by jjuli93** [comment]
Why is this closed? Is there no plan support typescript?

**Comment by luis-ryestrategy** [comment]
Is there a custom implementation somewhere? I don't think we're going to get an official one anytime soon

**Comment by thamilmurugesan** [comment]
oh wow, 2024 is gonna end, and we didnt receive it yet.

**Comment by alii-7** [comment]
Any updates on this ?

**Comment by hiago-b-oliveira** [comment]
Hello from 2025 😬

**Comment by manasseh-zw** [comment]
To this day gif

**Comment by torchsmith** [comment]
Sad

**Comment by rajeshgupta723** [comment]
@torchsmith @manasseh-zw @hiago-b-oliveira @alii-7 @thamilmurugesan @luis-ryestrategy @jjuli93 @kuang @ananay 

Hi, picked up and started the typescript support with updating the branch "typescript": https://github.com/intuit/oauth-jsclient/tree/typescript

Please have a look, review and feel free to add your contributions to this branch for adding support for the typescript.
Appreciate your contributions!

Thanks!

**Comment by kuang** [comment]
Thank you!

**Comment by ohabash** [comment]
> [@torchsmith](https://github.com/torchsmith) [@manasseh-zw](https://github.com/manasseh-zw) [@hiago-b-oliveira](https://github.com/hiago-b-oliveira) [@alii-7](https://github.com/alii-7) [@thamilmurugesan](https://github.com/thamilmurugesan) [@luis-ryestrategy](https://github.com/luis-ryestrategy) [@jjuli93](https://github.com/jjuli93) [@kuang](https://github.com/kuang) [@ananay](https://github.com/ananay)
> 
> Hi, picked up and started the typescript support with updating the branch "typescript": https://github.com/intuit/oauth-jsclient/tree/typescript
> 
> Please have a look, review and feel free to add your contributions to this branch for adding support for the typescript. Appreciate your contributions!
> 
> Thanks!

I cant tell if this is a solution? or an effort?
