### ISSUE TITLE
client support for autoRefresh on the access token

### ISSUE THREAD

**Issue by abisalehalliprasan** [intuit/oauth-jsclient#34]
Goal : 
The client should handle refreshing the access tokens before the expiry ( once every hour ). This feature should be `optional` and should be able to available during the time of instantiation of oAuthClient as shown below  
```var oauthClient = new OAuthClient({
    clientId: '<Enter your clientId>',
    clientSecret: '<Enter your clientSecret>',
    environment: 'sandbox' || 'production',
    redirectUri: '<Enter your callback URL>'
    autoRefresh: true  // default false
});```

**Comment by sthang** [comment]
I would like to be assigned to this issue for hacktoberfest.

**Comment by vibu267** [comment]
@sthang Are you working on this? I would like to pick it up if you are not.

**Comment by sthang** [comment]
@vibu267 I'm working on this. Thanks for asking.

**Comment by ch3rr17** [comment]
@abisalehalliprasan I would like to look into this too as well.

**Comment by brunocascio** [comment]
Any progress here? I'm facing an issue with `refresh()` method (error invalid_grant)

**Comment by abisalehalliprasan** [comment]
@brunocascio : This issue was created as an enhancement request. The PR is yet to be tested. 

However, if your concern is just regarding the error `invalid_grant` Could you provide the intuit-tid from response headers when the refresh() call is made ? 

There could be many reasons : 

- Access/Refresh token might be expired, corrupted
- User is no longer an admin etc 

If you want to contact our support team, you can find all the details on our support page  : https://help.developer.intuit.com/s/
