### ISSUE TITLE
Strict mode keywords

### ISSUE THREAD

**Issue by rickygarg** [intuit/oauth-jsclient#4]
There is some occasional use of strict mode keywords, such as 

var package = require('../package.json');

This makes it difficult to use in an ES6 project. Appreciate if you could modify or suggest a workaround.

**Comment by abisalehalliprasan** [comment]
@rickygarg : Will consider getting changes included to the ES6 module in the next releases.

**Comment by adam-t-b** [comment]
@abisalehalliprasan Any work arounds for this? Or any update on when this might get picked up for work?

**Comment by abisalehalliprasan** [comment]
@adam-t-b : Are you minifying the package in your app? We could probably rename the package to version as shown below : 
`var version = require('../package.json')` 

would that work?
