### ISSUE TITLE
Does this library support any HTTP methods for API calls other than GET?

### ISSUE THREAD

**Issue by brycejech** [intuit/oauth-jsclient#40]
Reading through the client code, it doesn't appear as though any of the other HTTP methods such as PUT, POST, or DELETE are supported. Unless I'm reading something wrong it looks like this only supports the token handling and GET requests for API calls.

If that is the case are there any plans to support other HTTP methods with body contents or am I better off using a third-party lib or rolling something myself?

Thanks!

**Comment by abisalehalliprasan** [comment]
@brycejech : The `oauth-jsclient` was initially created for token generation purposes and rightfully so we did not support other HTTP methods. The GET method was used to make sure the access/refresh token works with the `CompanyInfo` endpoint. 

But I hear your point. The fix should be easy. Let me provide support for PUT,POST,DELETE for now. However kindly be advised that it would not be a full-blown SDK to support V3 API calls but you can still use it support the above-mentioned HTTP methods.   

Thanks @brycejech

**Comment by brycejech** [comment]
Awesome, thanks!!

I see you guys have some issues tagged Hacktoberfest already. Mind if I take a stab at this one and send you a PR instead?

**Comment by abisalehalliprasan** [comment]
@brycejech : Sure. Go for it. I'd assign you on this one. Kindly send a PR to the `develop` branch.
