### ISSUE TITLE
The sample does not work out-of-the-box

### ISSUE THREAD

**Issue by skyarkitekten** [intuit/oauth-jsclient#5]
There are a few issues with the provided sample code.

1. When a user clones the repo and goes follows the instructions for the **sample** README, the application refuses to start. This is because the sample code reference the local client code and not what is installed via NPM

2. When using NPM, the package.json references v1.0.2 of the client but the current codebase is v1.0.3.

3. The Get Company Info use case does not work.

**Comment by skyarkitekten** [comment]
Thanks for the quick feedback @abisalehalliprasan, much appreciated!

**Comment by cyberwombat** [comment]
So sample still does not work - the callback action has no reference to oauthClient. I am unable to get my code to run nor can I get the sample to work even when I fix this so Id love to see an actual piece of working code.

**Comment by abisalehalliprasan** [comment]
@cyberwombat :  You might have got confused with the callback URI. Just follow the instructions listed on the sample [README.md](https://github.com/intuit/oauth-jsclient/tree/master/sample) and you should be able to authenticate using this library. 

If you are seeing a different error, please provide the screenshot and we can look into it.

**Comment by cyberwombat** [comment]
@abisalehalliprasan - my bad - I was looking at this from my need which is stateless hence my issue with empty oauthClient.
