### ISSUE TITLE
GetUser method does not work in sandbox

### ISSUE THREAD

**Issue by skyarkitekten** [intuit/oauth-jsclient#6]
When we attempt to get the user info with the `getUserInfo` method in the OAuthClient, we recieve an error. I believe that the call to the identity endpoint is not respecting the environment parameter and/or not getting the endpoint from the discovery document.

In the error message, the response says it is coming from `https://accounts.platform.intuit.com/v1/openid_connect/userinfo` but the documentation says that the sandbox endpoint for user info should be `https://sandbox-accounts.platform.intuit.com/v1/openid_connect/userinfo`

**Comment by abisalehalliprasan** [comment]
@skyarkitekten ,

Thanks for pointing this out. Will add this to the next release and provide an update. Apologize for the inconvenience caused.

**Comment by abisalehalliprasan** [comment]
@skyarkitekten : This fix is provided in the new release [1.1.0](https://github.com/intuit/oauth-jsclient/tree/1.1.0) Thanks for pointing it out !
