### ISSUE TITLE
Why does sample use global instance of OAuthClient?

### ISSUE THREAD

**Issue by jlc467** [intuit/oauth-jsclient#61]
All of the sample code seems to revolve around a single company integration. Who is building integrations for a single company? Far more common is an integration designed to work with multiple companies. This was brought up here: https://github.com/intuit/oauth-jsclient/issues/1

Not sure why the sample code / documentation is built for a very uncommon use case.

**Comment by abisalehalliprasan** [comment]
@jlc467 : The library is an OAuth client library and not a full-blown SDK. 

When we designed this initially, we did expose helper methods to get/set the tokens associated with multiple companies, so that we could use just one instance of OAuthClient.
