### ISSUE TITLE
Mistake in code example

### ISSUE THREAD

**Issue by jamesmogg** [intuit/oauth-jsclient#63]
There is a mistake in the code example for refreshing an access token.
line 3 reads

`console.log('Tokens refreshed : ' + JSON.stringify(authResponse.json()))`

it should be

`console.log('Tokens refreshed : ' + JSON.stringify(authResponse.getJson()))`

The original code throws an error, which isn't immediately apparent as the error handling is looking for errors from the intuit api, and not from the callback, so it appears as undefined unless you look at the raw error.

**Comment by MotorCityCobra** [comment]
Another mistake is...  

    openid - for openID assertion include OAuthClient.scopes.Openid

It should be  

    openid - for openID assertion include OAuthClient.scopes.OpenId

Spent 45 minutes trying with and without every scope. Thanks H1B system!

**Comment by abisalehalliprasan** [comment]
Thanks @MotorCityCobra and @jamesmogg . Documentation is fixed in the release [2.0.1](https://github.com/intuit/oauth-jsclient/tree/2.0.1#scopes)
