### ISSUE TITLE
I've been trying all day and can't figure out how the API gets authorized

### ISSUE THREAD

**Issue by MotorCityCobra** [intuit/oauth-jsclient#64]
@kyleabens : 

said...
So for your app, you could have this process : 
`setToken(authToken) -> isAccessTokenValid() -> MakeAPICall()`

It's not clear if this is for a user to authorize an app. I don't need that. I need to make an API call. It's not clear from the main page how I get the token to send to and receive from the API.

**Comment by joel-deleon-tg** [comment]
@MotorCityCobra did you find out how to do this? I assume all you wanted was to allow external users to talk to QBO APIs, unfortunately documentation is not clear and following the steps would lead the users to a sign in page they should not use.
