### ISSUE TITLE
revoke function response does not support getJson()

### ISSUE THREAD

**Issue by AlbertHambardzumyan** [intuit/oauth-jsclient#73]
According to [Revoke access_token documentation](https://www.npmjs.com/package/intuit-oauth#revoke-access_token) I should be able to call `getJson()` on the response:

```
  const authResponse = await oauthClient.revoke(token)
  console.log('Token revoked', authResponse.getJson())
```
However, Im getting the following error: 
`Error: AuthResponse is not JSON`

Any thoughts ?

**Comment by abisalehalliprasan** [comment]
@AlbertHambardzumyan : The `revoke()` does not return the JSON. I will fix this and release a new version. 

However, in the meantime you could see the status of the revoke() using : 
`authResponse.response.status`

**Comment by AlbertHambardzumyan** [comment]
@abisalehalliprasan 
I just need token itself, no need the response status at all.
Turns out the response of `revoke()` call is the token I'm looking for.

So, I would say the documentation describes this api wrongly.

**Comment by abisalehalliprasan** [comment]
Welcome any PR's. I will also get this fixed in the new release. Thanks @AlbertHambardzumyan
