### ISSUE TITLE
JSDoc wrongly describes IntuitOauth constructor  argument

### ISSUE THREAD

**Issue by AlbertHambardzumyan** [intuit/oauth-jsclient#76]
Describes as [constructor JSDoc](https://github.com/intuit/oauth-jsclient/blob/master/src/OAuthClient.js#L45)
However, it suppose to be [constructor doc](https://github.com/intuit/oauth-jsclient#using-nodejs)

Thus, editor complains when we have 
```
 new IntuitOauth({
  clientId: '',
  clientSecret: ''
  environment: '',
  redirectUri: ''
})
```

**Comment by abisalehalliprasan** [comment]
I am not following you. could you send a PR ?

**Comment by AlbertHambardzumyan** [comment]
@abisalehalliprasan 
Don't hurry to close the issue. Moreover, you could not follow it.
People spend time to point out the bugs, please appreciate that. 

You have a wrong JSDoc [here](https://github.com/intuit/oauth-jsclient/blob/master/src/OAuthClient.js#L45)
```
/**
 * @constructor
 * @param {string} config.environment
 * @param {string} config.appSecret
 * @param {string} config.appKey
 * @param {string} [config.cachePrefix]
 */
function OAuthClient(config) {
  ...
}
```

**Comment by abisalehalliprasan** [comment]
@AlbertHambardzumyan : I understand your concern here. But if you are not going to provide more details it will not help in getting the issue resolved. 

If you think there is something wrong here could you add a PR to fix this?

**Comment by AlbertHambardzumyan** [comment]
@abisalehalliprasan 
As you see, I have spent more time and provided more details. However, the issue itself is closed already.
That's weird to ask for a PR, but close the issue at the same time.

If something is not clear enough yet, it does not mean the issue can be considered as resolved by simply closing it.
This is unexceptable.

Never mind. Thats already clear to me that some other tool should be used instead of this one.
Again, this is unexceptable. No one does this in a way you do.
