### ISSUE TITLE
`snyk` package as a dependency since the 3.0 version

### ISSUE THREAD

**Issue by Grmiade** [intuit/oauth-jsclient#88]
In this [commit](https://github.com/intuit/oauth-jsclient/commit/18ab287e1eeb8ee31134c22e4e0f907b64f94fbb), you introduced `snyk` as a dependency. Do you think you could migrate it to a dev dependency?
With the 3.0 version, all the snyk library and its dependencies are installed on our machines when we use the `intuit-oauth` library :/

**Comment by abisalehalliprasan** [comment]
Will fix get this fixed by tomorrow 👍

**Comment by abisalehalliprasan** [comment]
Fixed in the new release `3.0.1`. Closing the issue @Grmiade

**Comment by Grmiade** [comment]
Thanks @abisalehalliprasan
Very responsive 💪
