### ISSUE TITLE
realmId field is blank on auth response in new version

### ISSUE THREAD

**Issue by ZachJames** [intuit/oauth-jsclient#9]
Hi,
I recently updated from version 1.0.2 to 1.1.0 and the response received to my callback has a blank token.realmId property, which is just an empty string. I am using createToken(). 

Tested on 1.0.2 with same logic and it's populated. Please advise.

Thanks

**Comment by abisalehalliprasan** [comment]
@ZachJames : I had incorporated some changes in version `1.1.0` which resulted in the blank `realmId` on the token object. 

Could you please try using version `1.1.1` and let us know if its working as expected ?

**Comment by ZachJames** [comment]
Yes, I can now see the realmId. It's fixed.

Thanks for the quick update!
