### ISSUE TITLE
AuthResponse is not JSON

### ISSUE THREAD

**Issue by dbowmanDT** [intuit/oauth-jsclient#91]
Plugin Version: 3.0.1

Calling the makeApiCall function threw this error.

Error: Processing a request Error: AuthResponse is not JSON
        at AuthResponse.getJson (/home/dbowman/dtr-code/beacon/node_modules/.pnpm/registry.npmjs.org/intuit-oauth/3.0.1/node_modules/intuit-oauth/src/response/AuthResponse.js:106:29)
        at OAuthClient.createError (/home/dbowman/dtr-code/beacon/node_modules/.pnpm/registry.npmjs.org/intuit-oauth/3.0.1/node_modules/intuit-oauth/src/OAuthClient.js:571:31)

Looks like the response returned from QBO API was not JSON content. 

Please advise.

**Comment by abisalehalliprasan** [comment]
Could you provide the `Request Payload` and `Response headers` if possible?

**Comment by dbowmanDT** [comment]
message: "Error: Processing a request Error: Response has an Error
    at /beacon/pnpm-store/node_modules/.pnpm/registry.npmjs.org/intuit-oauth/3.0.1/node_modules/intuit-oauth/src/OAuthClient.js:511:40
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async updateQBORefresh (/beacon/pnpm-store/node_lib/quickbooks_online/src/qbo.js:143:5)
    at async retryWhenMisMatch (/beacon/pnpm-store/node_lib/lcs_node/src/retry.js:8:24)
    at async checkAndRefresh (/beacon/pnpm-store/node_lib/quickbooks_online/src/qbo.js:169:12)
    at async searchEntity (/beacon/pnpm-store/node_lib/quickbooks_online/src/qbo.js:273:25)
    at async getPagedResult (/beacon/src/pagedResults.js:47:18)
    at async processRequest (/beacon/pnpm-store/node_lib/interface_web/src/web.js:388:16) {
  authResponse: AuthResponse {
    token: Token {
      realmId: '4620816365062705900',
      token_type: 'bearer',
      access_token: '<my access token>',
      refresh_token: '<my refresh token>',
      expires_in: 3600,
      x_refresh_token_expires_in: 8643035,
      id_token: '',
      latency: 60000,
      createdAt: 1591374888215
    },
    response: Response {
      Url: Url {
        protocol: 'https:',
        slashes: true,
        auth: null,
        host: 'oauth.platform.intuit.com',
        port: null,
        hostname: 'oauth.platform.intuit.com',
        hash: null,
        search: null,
        query: [Object: null prototype] {},
        pathname: '/oauth2/v1/tokens/bearer',
        path: '/oauth2/v1/tokens/bearer',
        href: 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer'
      },
      rawHeaders: [
        'Date',
        'Fri, 05 Jun 2020 19:23:38 GMT',
        'Content-Type',
        'application/json;charset=utf-8',
        'Content-Length',
        '25',
        'Connection',
        'close',
        'Server',
        'nginx',
        'Strict-Transport-Security',
        'max-age=15552000',
        'intuit_tid',
        '1-5eda9bba-f3286d384652894017c1e360',
        'x-spanid',
        'e7a64a44-ce71-4e2f-bc69-ddfada22d334',
        'x-amzn-trace-id',
        'Root=1-5eda9bba-f3286d384652894017c1e360',
        'x-spanid',
        '3d754d2f-21ec-4ff0-b563-d090b0d2f8ed:1',
        'x-amzn-trace-id',
        'Self=1-5eda9bba-9f8a28bae2f0e6467237ce36;Root=1-5eda9bba-f3286d384652894017c1e360',
        'Cache-Control',
        'no-cache, no-store',
        'Pragma',
        'no-cache'
      ],
      body: '{"error":"invalid_grant"}',
      status: 400,
      statusText: 'Bad Request'
    },
    body: '{"error":"invalid_grant"}',
    json: { error: 'invalid_grant' },
    intuit_tid: '1-5eda9bba-f3286d384652894017c1e360'
  },
  originalMessage: 'Response has an Error',
  error: 'invalid_grant',
  error_description: 'Bad Request',
  intuit_tid: '1-5eda9bba-f3286d384652894017c1e360'
}

**Comment by dbowmanDT** [comment]
Request was to the sandbox environment:
/v3/company/<realmId>/query?query=select Name, Id from Item Where Type = 'Service' and Name like '%' startposition 0 maxresults 10

I do not have the response headers, I should have put them in the issue when I encountered the error. I do not know how to reproduce consistently.

**Comment by abisalehalliprasan** [comment]
@dbowmanDT : The query that was passed to the `makeApiCall()` was not URI-encoded. 

The query you are trying to use is : 
```
select Name, Id from Item Where Type = 'Service' and Name like '%' startposition 0 maxresults 11
```
You can pass the query using `makeApiCall()` as shown below :  ( minorversion is  **optional** )
``` 
makeApiCall({
      url: `${url}v3/company/${companyID}/query?query=select%20Name%2C%20Id%20from%20Item%20Where%20Type%20%3D%20%27Service%27%20and%20Name%20like%20%27%25%27%20startposition%200%20maxresults%2011&minorversion=51`,
    })
```

For now, you can use the above-mentioned workaround. 

Since this is an `OAuth2.0` library, we will think about how to add this to a full-fledged SDK.

**Comment by akila-arasan** [comment]
@abisalehalliprasan @dbowmanDT  I am also facing the same issue, I digged into the source code and  the problem was in the `processresponse` method. 

`AuthResponse.prototype.processResponse = function processResponse(response) {
  this.response = response || '';
  this.body = (response && response.body) || '';
  this.json = this.body ? JSON.parse(this.body) : null; // JSON.parse is failing.
  this.intuit_tid = (response && response.headers && response.headers.intuit_tid) || '';
};`

the response body value returned as follows,

` body: '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2020-08-17T02:01:11.228-07:00"><Fault type="AuthenticationFault"><Error code="100"><Message>General Authentication Error</Message><Detail>AuthenticationErrorGeneral: SRV-110-Authentication Failure , statusCode: 401</Detail></Error></Fault></IntuitResponse>'`

As the body is returned in xml it is failing in process response.

Also, I make api call only if the `oauthClient.isAccessTokenValid()`  returns true. However there is authentication error. Am I missing some thing? 

the query is `select * from Account where AccountType = 'Cost of Goods Sold'`

Please help.

**Comment by abisalehalliprasan** [comment]
@akila-arasan : Tried to reproduce the error and I am not running into the same issue. I am suspecting if there is a mismatch with the Base URL used to make the API call and the Keys provided. When a token is invalid the SDK throws an error with the below format ( secure details are _masked_ ) 

```
  authResponse: AuthResponse {
    token: Token {
      realmId: '462xxxxxxxxxxx867780',
      token_type: 'bearer',
      access_token: 'eyJlbmMixxxxxxxxxxxxxFFxk-hjxtA',
      refresh_token: 'AB11606448419RxxxxxxxxxxxxxxxxxxxxgRlWpTn0xFffVpoq',
      expires_in: 3600,
      x_refresh_token_expires_in: 8726400,
      id_token: '',
      latency: 60000,
      createdAt: 1597722019184,
      state: 'intuit-test'
    },
    response: Response {
      Url: [Url],
      rawHeaders: [Array],
      body: '{"warnings":null,"intuitObject":null,"fault":{"error":[{"message":"message=AuthenticationFailed; errorCode=003200; statusCode=401","detail":"Could not decrypt JWT.","code":"3200","element":null}],"type":"AUTHENTICATION"},"report":null,"queryResponse":null,"batchItemResponse":[],"attachableResponse":[],"syncErrorResponse":null,"requestId":null,"time":1597722025429,"status":null,"cdcresponse":[]}',
      status: 401,
      statusText: 'Unauthorized'
    },
    body: '{"warnings":null,"intuitObject":null,"fault":{"error":[{"message":"message=AuthenticationFailed; errorCode=003200; statusCode=401","detail":"Could not decrypt JWT.","code":"3200","element":null}],"type":"AUTHENTICATION"},"report":null,"queryResponse":null,"batchItemResponse":[],"attachableResponse":[],"syncErrorResponse":null,"requestId":null,"time":1597722025429,"status":null,"cdcresponse":[]}',
    json: {
      warnings: null,
      intuitObject: null,
      fault: [Object],
      report: null,
      queryResponse: null,
      batchItemResponse: [],
      attachableResponse: [],
      syncErrorResponse: null,
      requestId: null,
      time: 1597722025429,
      status: null,
      cdcresponse: []
    },
    intuit_tid: '1-5f3b4da9-087a28ed878e2215f4eb3a28'
  },
  originalMessage: 'Response has an Error',
  error: 'Unauthorized',
  error_description: 'Unauthorized',
  intuit_tid: '1-5f3b4da9-087a28ed878e2215f4eb3a28'
}
```

Could you share the sample code snippet where you are performing the query `select * from Account where AccountType = 'Cost of Goods Sold'` that would help us debug the question at hand? 
**OR** 
if you could provide the intuit_tid / appID and timestamp of the request I could run by the logs to see what is missing.

**Comment by akila-arasan** [comment]
@abisalehalliprasan  Thanks for debugging.

The Base URL that I use to make the query is - ` https://sandbox-quickbooks.api.intuit.com/v3/company/realmId/query?query= select * from Account where AccountType = 'Cost of Goods Sold'`

After establishing a connection between QB and our app, we try to export items to inventory, we need to check if the company has a income / expense account before adding items to inventory, that's why we make the above call. 

the code snippet for the above api call is 

```
const accountNameList = await oauthClient.makeApiCall({
    url: `${QBUrl}v3/company/${realmId}/query?query=${query}`,
  })
    .then((res) => {
      customSetToken(oauthClient, res.token);
      return res;
    })
    .catch(function(err) {
      return err;
    })
```
the realmID is - `4620816365033885370`
timestamp - `1597738603040`


But the question here is `oauthClient.isAccessTokenValid()` call returns `true` only after that I make the call to query account. So if there is an authentication failure shouldn't this `oauthClient.isAccessTokenValid()`  fail?

**Comment by abisalehalliprasan** [comment]
I looked up our logs based on the realmID and timestamp you provided. It looks like you are making the call for an incorrect realm. The realm from the logs for the specific error shows ( 193514846595064 ) for the exact timestamp you provided. 

And hence the `oauthClient.isAccessTokenValid()` is returning `true` as the token is still valid. ( under 1 hour duration ) 

I was able to reproduce the same error with the incorrect token/realm combination as shown below :
```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2020-08-18T21:08:26.926-07:00">
    <Fault type="AuthenticationFault">
        <Error code="100">
            <Message>General Authentication Error</Message>
            <Detail>AuthenticationErrorGeneral: SRV-110-Authentication Failure , statusCode: 401</Detail>
        </Error>
    </Fault>
</IntuitResponse>
```
Could you verify if your application is able to associate the token object with realmID based on the storage mechanism that you are using? This should hopefully **fix** the issue. 

As for the above error format XML handling, I will put in a PR for the next release.

**Comment by akila-arasan** [comment]
@abisalehalliprasan Thanks ! The problem was in the cron that refreshes expired QB access tokens. Now the associations are correct.

**Comment by abisalehalliprasan** [comment]
Awesome. I will mark it as resolved. 👍

**Comment by RicardoAReyes** [comment]
Hi @abisalehalliprasan do you have a timetable for when you plan to submit the PR for this issue? Our team would like to test our app with this AuthReponse JSON fix and plan accordingly. Thank you.

**Comment by Jebble** [comment]
@abisalehalliprasan what exactly is the solution to this error? Response returns XML without anything for us to read error wise. It's quite impossible to find out why API calls are failing. Please assist

**Comment by Isaacmeedinaa** [comment]
Has this been resolved?

**Comment by degardinn** [comment]
Hi! I have the same issue with some endpoints such as `/v3/company/123146326763614/companyinfo/1?minorversion=40`

In my case, the SDK `src/response/AuthResponse.js` `isJson` function (l.147) is looking for the response *Content-Type* header containing `application/json` while it contains `application/json;charset=utf-8`.
