### ISSUE TITLE
v3 migration documentation

### ISSUE THREAD

**Issue by AlbertHambardzumyan** [intuit/oauth-jsclient#94]
Trying to upgrade version from v2  to v3, but feeling hard to identify the breaking changes.
Some changelog or migration doc would be helpful.

**Comment by abisalehalliprasan** [comment]
You can refer to [CHANGELOG.md](https://github.com/intuit/oauth-jsclient/blob/master/CHANGELOG.md#300). This was introduced due to address a vulnerability caused by [mocha](https://travis-ci.org/github/intuit/oauth-jsclient/jobs/685905894)

**Comment by AlbertHambardzumyan** [comment]
Only v1 was documented at the time when I was checked it yesterday.

Now, I can see v3 too. That's exactly what I wanted.
