### ISSUE TITLE
Payment scope

### ISSUE THREAD

**Issue by cwil423** [intuit/oauth-jsclient#96]
Why does this cause an error but if I remove the third scope it does not?
const authURI = oauthClient.authorizeUri({
    scope: [OAuthClient.scopes.Accounting, OAuthClient.scopes.OpenId, OAuthClient.scopes.Payment],
    state: 'testState',
});

**Comment by abisalehalliprasan** [comment]
@cwil423 : Is the production QBO company that you are trying to connect Payments enabled?If so, you would need to have a Production QBO company with Payments [enabled](https://quickbooks.intuit.com/ca/tutorials/set-use-quickbooks-payments/#:~:text=Go%20to%20your%20Company%20Settings,Up%20Payments%20to%20get%20started.)

However, If you are testing using a sandbox QBO company, Payments are enabled by default as described [here](https://developer.intuit.com/app/developer/qbpayments/docs/develop/sandboxes#launch-a-sandbox)
