### ISSUE TITLE
PDF Transport

### ISSUE THREAD

**Issue by haislip** [intuit/oauth-jsclient#97]
This library currently does not seem to actually work when pulling the generated PDF files from an environment.  It's relying on the default transport options from the popsicle libraries, which is `text`.  This means that we get a text representation of the PDF instead of the actual buffer that we need in order to save the file once we've received it.  If you save/view the PDF response without this, it just appears as a blank document.

I've hacked working solution together [here](https://github.com/intuit/oauth-jsclient/compare/master...haislip:master) that gets this to work by allowing the user to pass in the transport directly (and defaults back to `text` when it's not provided).

**Comment by abisalehalliprasan** [comment]
Thanks, @haislip for coming up with a quick fix. We are currently opening up our SDK's for contributions : [hacktoberfest](https://hacktoberfest.digitalocean.com/).  

As you have already provided the suggestion Could you create a PR, please?

**Comment by haislip** [comment]
Hacktastic: https://github.com/intuit/oauth-jsclient/pull/98

**Comment by abisalehalliprasan** [comment]
@haislip . Thanks for the contribution. Will review the PR's soon 🚀

**Comment by krishnal** [comment]
@abisalehalliprasan Is there any possibility you can review and merge this?

`/v3/company/${companyID}/invoice/${invoiceId}/pdf` Download pdf API is really not working without this. 

Many thanks!
